/*
 * BruceHurrican
 * Copyright (c) 2016.
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *
 *    This document is Bruce's individual learning the android demo, wherein the use of the code from the Internet, only to use as a learning exchanges.
 *    And where any person can download and use, but not for commercial purposes.
 *    Author does not assume the resulting corresponding disputes.
 *    If you have good suggestions for the code, you can contact BurrceHurrican@foxmail.com
 *    本文件为Bruce's个人学习android的作品, 其中所用到的代码来源于互联网，仅作为学习交流使用。
 *    任和何人可以下载并使用, 但是不能用于商业用途。
 *    作者不承担由此带来的相应纠纷。
 *    如果对本代码有好的建议，可以联系BurrceHurrican@foxmail.com
 */

package bruce.kk.brucetodos.database.bean;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;
import org.greenrobot.greendao.annotation.Property;
import org.greenrobot.greendao.annotation.Unique;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "t_todo".
 */
@Entity(nameInDb = "t_todo")
public class UnFinishItem implements Comparable<UnFinishItem> {

    @Id(autoincrement = true)
    @Unique
    public Long id;

    @Property(nameInDb = "createDay")
    @NotNull
    public java.util.Date createDay;

    @Property(nameInDb = "content")
    @NotNull
    public String content;

    @Property(nameInDb = "modifyDay")
    @NotNull
    public java.util.Date modifyDay;

    @Property(nameInDb = "finishDay")
    public java.util.Date finishDay;

    @Generated(hash = 975478401)
    public UnFinishItem() {
    }

    public UnFinishItem(Long id) {
        this.id = id;
    }

    @Generated(hash = 1845291860)
    public UnFinishItem(Long id, @NotNull java.util.Date createDay, @NotNull String content, @NotNull java.util.Date modifyDay, java.util.Date finishDay) {
        this.id = id;
        this.createDay = createDay;
        this.content = content;
        this.modifyDay = modifyDay;
        this.finishDay = finishDay;
    }

    @Override
    public int compareTo(UnFinishItem unFinishItem) {
//        if (this.costDay != another.costDay) {
//            return this.costDay - another.costDay; // 按 costDay 升序
//            return another.costDay - this.costDay; // 按 costDay 降序
//        } else {
        // 按 costModifyDate.getTime() 升序
//            return (int) (this.costModifyDate.getTime() - another.costModifyDate.getTime());
        // 按 costModifyDate.getTime() 降序
//            return (int) (another.costModifyDate.getTime() - this.costModifyDate.getTime());
//        }
        // 修改日期相同,按创建日期降序排序
        if (this.modifyDay.getTime() == unFinishItem.modifyDay.getTime()) {
            if (this.createDay.getTime() == unFinishItem.createDay.getTime()) {
                // 创建日期相同,按 id 降序排序
                return (int) (unFinishItem.id - this.id);
            } else {
                return (int) (unFinishItem.createDay.getTime() - this.createDay.getTime());
            }
        } else {
            // 修改日期不同,按修改日期降序排序
            return (int) (unFinishItem.modifyDay.getTime() - this.modifyDay.getTime());
        }
    }

    @Override
    public String toString() {
        return "UnFinishItem{" +
                "id=" + id +
                ", createDay=" + createDay +
                ", content='" + content + '\'' +
                ", modifyDay=" + modifyDay +
                ", finishDay=" + finishDay +
                '}';
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getCreateDay() {
        return this.createDay;
    }

    public void setCreateDay(java.util.Date createDay) {
        this.createDay = createDay;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public java.util.Date getModifyDay() {
        return this.modifyDay;
    }

    public void setModifyDay(java.util.Date modifyDay) {
        this.modifyDay = modifyDay;
    }

    public java.util.Date getFinishDay() {
        return this.finishDay;
    }

    public void setFinishDay(java.util.Date finishDay) {
        this.finishDay = finishDay;
    }
}
